apiVersion: v1
kind: Service
metadata:
  name: ticketserver
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
  type: NodePort
  selector:
    app: ticketserver
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ticket-ingress
spec:
  backend:
    serviceName: ticketserver
    servicePort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ticketserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketserver
  template:
    metadata:
      labels:
        app: ticketserver
    spec:
      containers:
      - image: gcr.io/default-1296/ticketserver:latest
        name: ticketserver
        env:
        - name: DBBACKEND
          value: 'mysql'
        - name: DBCONSTRING
          value: 'root:notsosecretpassword@tcp(mysql:3306)/'
        ports:
        - containerPort: 9001
          name: ticketserver